name: rescue_mesh_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  fcllama: ^0.0.3
  flutter_blue_plus: ^1.35.5
  llama_cpp_dart: ^0.2.0
  drift: ^2.19.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  path: ^1.9.0
  permission_handler: ^11.3.1
  location: ^5.0.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  connectivity_plus: ^6.0.3
  http: ^1.2.1
  shared_preferences: ^2.3.2
  screen_brightness: ^2.1.7
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.2.1
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.19.0
  build_runner: ^2.13.1
  riverpod_generator: ^4.0.3

dependency_overrides:
  sqlite3: 3.1.5

hooks:
  user_defines:
    sqlite3:
      source: system
      name_android: sqlite3

flutter:
  uses-material-design: true
  assets:
    - assets/models/
